---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

workspace:
  base: /root/go
  path: src/github.com/presslabs/dashboard

steps:
- name: git
  pull: if-not-exists
  image: plugins/git
  settings:
    depth: 100
    tags: true

- name: publish-graphite-web
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: graphite-web
    dockerfile: graphite-web/Dockerfile
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/graphite-web
    tags:
    - ${DRONE_TAG:-${DRONE_BRANCH/master/latest}}
    - ${DRONE_COMMIT_SHA:0:8}
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    event:
    - push

- name: publish-go-carbon
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: go-carbon
    dockerfile: go-carbon/Dockerfile
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/go-carbon
    tags:
    - ${DRONE_TAG:-${DRONE_BRANCH/master/latest}}
    - ${DRONE_COMMIT_SHA:0:8}
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    event:
    - push

---
kind: signature
hmac: cdb4f35574cd0fc9e36b91e5bc1a39d26ac26bc9446a4920ec938fac577f7769

...
