---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

workspace:
  base: /root/go
  path: src/github.com/presslabs/dashboard

steps:
- name: git
  pull: if-not-exists
  image: plugins/git
  settings:
    depth: 100
    tags: true

- name: publish-graphite-web
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: graphite-web
    dockerfile: graphite-web/Dockerfile
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/graphite-web
    tags:
    - latest
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    branch:
    - master
    event:
    - push

- name: publish-go-carbon
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: go-carbon
    dockerfile: go-carbon/Dockerfile
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/go-carbon
    tags:
    - latest
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    branch:
    - master
    event:
    - push

...
